#!/bin/sh

LOG="$HOME/.config/X11/xinitrc.log"
ERR="$HOME/.config/X11/xinitrc.errors.log"
session_logfile="$HOME/.config/X11"/"$(date +%s)".log

rm "$LOG"
rm "$ERR"
touch "$LOG"
touch "$ERR"

exec 1> >(tee "$LOG")
exec 2> >(tee "$ERR" >&2)

export PATH="$PATH:/home/fewcm/.local/bin"
export PATH="$PATH:/home/fewcm/.local/bin/dwm"

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrdb /home/fewcm/.config/X11/xresources

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval `dbus-launch --sh-syntax --exit-with-x11`
	echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi

# Kill already running process
_ps=(compton picom dunst wired polybar)
for _prs in "${_ps[@]}"; do
    if [[ $(pidof ${_prs}) ]]; then
        killall -9 ${_prs}
    fi
done

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(gnome-keyring-daemon --start --components=pkcs11,secrets)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets)
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

xrandr --output HDMI-0 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output DVI-D-0 --mode 1920x1080 --pos 2560x0 --rotate normal &

# Restore wallpaper


# Lauch daemon
#start dunst -c $HOME/.config/dunst/dunstrc &
wired -r &
#greenclip daemon &
playerctld daemon &
ibus-daemon -drxR &
#dwmcomp &
picom --experimental-backends --daemon --config $HOME/.config/picom/picom.conf  &

pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1 &

# Increase key speed via a rate change
xset r rate 300 50
xset b off
xset m 3/2 0
xset -dpms 

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R'
xmodmap -e 'clear control' -e 'add control = Control_L' -e 'clear mod3' -e 'add mod3 = Control_R'

# Fix cursor
xsetroot -cursor_name left_ptr

indicator-sound-switcher &
unclutter &
#dwmbar & 

setbg &

exec dwm

