command_key=':'
use_nerdfont=true
flip_status_indicators=true
audio_cache=true
volnorm=true
notify=false
bitrate=320
album_column=false
shuffle=true
repeat='playlist'
default_keybindings=false

[keybindings]
"?"="help"
"q"="back"
"Shift+q"="quit"
"Backspace"="back"

"k"="move up"
"j"="move down"
"h"="move left"
"l"="move right"
"Up"="move up"
"Down"="move down"
"Left"="move left"
"Right"="move right"
"Home"="move top"
"End"="move bottom"

"n"="next"
"Shift+n"="previous"

"Shift+j"="shift down"
"Shift+k"="shift up"
"Shift+Up"="shift up"
"Shift+Down"="shift down"

"Shift+h"="seek -10000"
"Shift+l"="seek +10000"

"Space"="playpause"
"p"="playpause"
"Shift+p"="play"
"Enter"="play"
"Shift+Enter"="queue"
"Ctrl+p"="queue"
"Ctrl+Shift+p"="stop"

"Ctrl+d"="focus library"
"Ctrl+a"="focus queue"
"Ctrl+s"="focus search"
"F1"="focus library"
"F2"="focus queue"
"F3"="focus search"

"z"="shuffle"
"r"="repeat"

"Delete"="delete"
"Shift+Delete"="clear"

"o"="open selected"
"Shift+o"="open current"

"="="volup 5"
"-"="voldown 5"
"+"="volup 1"
"_"="voldown 1"

"a"="goto album"
"Shift+a"="goto artist"

# Gruvbox dark [ originally based on base16 by Dawid Kurek (dawikur@gmail.com) ]
[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_selected = "light green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"

